/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import himevico.GestorBBDD;
import himevico.VInicioAdministracion;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
=======
import himevico.VInicio;
>>>>>>> master
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheila
 */
public final class VLogin extends javax.swing.JFrame {
    
    private GestorBBDD db;
    
    /**
     * Creates new form VInicio
     */
    public VLogin() {
         initComponents();
<<<<<<< HEAD
         // Poner icono ventana
        
 

    // this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..imagenes/password.png")));
        
    }
    
        
    public VLogin(GestorBBDD db) {
=======
         
         // Centrar ventana
         this.setLocationRelativeTo(null);
      
    }
   
     
    /*public VLogin(GestorBBDD db) {
>>>>>>> master
        initComponents();
        this.db=db;
        
       
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jContrasena = new javax.swing.JPasswordField();
        jIniciarSesión = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRecordarContrasena = new javax.swing.JCheckBox();
        jUsuario = new javax.swing.JTextField();
        jFondoLock = new javax.swing.JLabel();
        jFondoVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Usuario: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));
        getContentPane().add(jContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, -1));

        jIniciarSesión.setBackground(new java.awt.Color(0, 51, 153));
        jIniciarSesión.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jIniciarSesión.setText("Iniciar sesión");
        jIniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarSesiónActionPerformed(evt);
            }
        });
        getContentPane().add(jIniciarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Contraseña: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jRecordarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        jRecordarContrasena.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRecordarContrasena.setText("Recordar contraseña");
        jRecordarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecordarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jRecordarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));
        getContentPane().add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, 20));

        jFondoLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lock.png"))); // NOI18N
        getContentPane().add(jFondoLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 250));

        jFondoVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoVentana inicio.png"))); // NOI18N
        getContentPane().add(jFondoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRecordarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecordarContrasenaActionPerformed
        // Recordar contraseña
        VRecordarContrasenaEscUsu vrceu = new VRecordarContrasenaEscUsu();
        vrceu.setVisible(true);
        
       

    }//GEN-LAST:event_jRecordarContrasenaActionPerformed

    @SuppressWarnings("static-access")
    private void jIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarSesiónActionPerformed
        // Iniciar sesión

        String usuario = jUsuario.getText();
        String contrasena = new String( jContrasena.getPassword());

        ResultSet rs;
        rs = db.comprobarUsuario(usuario,contrasena);
        try {
            if (rs.next()) {
                VInicioAdministracion inicio=new VInicioAdministracion();
                inicio.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "Error", "", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jIniciarSesiónActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Salir
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jContrasena;
    private javax.swing.JLabel jFondoLock;
    private javax.swing.JLabel jFondoVentana;
    private javax.swing.JButton jIniciarSesión;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox jRecordarContrasena;
    private javax.swing.JTextField jUsuario;
    // End of variables declaration//GEN-END:variables
}
 
